---
- name: update web servers
  hosts: 127.0.0.1
  remote_user: root

# Install/uninstall with chocolatey
- name: Ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip
    state: present